# Sphinx configuration for the JaxPP documentation.

import os
import re
import sys
from pathlib import Path

sys.path.insert(0, os.path.abspath("../src"))

import jaxpp

project = "jaxpp"
copyright = "2022-%Y, NVIDIA CORPORATION. All rights reserved"  # noqa: A001
author = "JaxPP authors"
version = jaxpp.__version__
release = jaxpp.__version__
language = "en"

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "myst_nb",
]

exclude_patterns = ["_build", "rendered", "README.md", "Thumbs.db", ".DS_Store"]

# Markdown pages with a kernelspec (file_format: mystnb) are notebooks: their
# code cells execute during the build and a failing cell fails the build.
nb_execution_mode = "force"
nb_execution_raise_on_error = True
nb_execution_show_tb = True
nb_execution_timeout = 300

myst_enable_extensions = ["deflist"]
myst_heading_anchors = 3

html_theme = "nvidia_sphinx_theme"
html_static_path = ["_static"]

autodoc_mock_imports = ["tensorboard", "graphviz"]


def _export_executed_markdown(app, exception):
    """Mirror the executed notebook pages as markdown, outputs included, into
    the committed docs/rendered/; CI fails if the committed copies are stale."""
    if exception is not None or app.builder.name != "html":
        return
    import nbconvert

    exporter = nbconvert.MarkdownExporter()
    dst = Path(__file__).parent / "rendered"
    dst.mkdir(exist_ok=True)
    for notebook in (Path(app.outdir).parent / "jupyter_execute").glob("*.ipynb"):
        body, _ = exporter.from_filename(str(notebook))
        body = re.sub("\x1b\\[[0-9;]*m", "", body)  # markdown cannot render ANSI colors
        name = notebook.with_suffix(".md").name
        header = f"<!-- Generated by the docs build from docs/{name}; do not edit. -->\n\n"
        (dst / name).write_text(header + body)


def setup(app):
    app.connect("build-finished", _export_executed_markdown)
